from uuid import uuid4
from finder_api.models import Cuisine
food_related = {
    "Afghan": "Traditional dishes featuring rice, lamb, and hearty stews, often flavored with dried fruits and nuts.",
    "African": "Diverse cuisines with bold flavors, including ingredients like yams, plantains, and spices.",
    "American": "Wide-ranging cuisine from burgers and barbecue to modern fusion dishes.",
    "Argentinean": "Known for grilled meats, empanadas, and Malbec wines.",
    "Armenian": "Features dishes like kebabs, lavash bread, and dolma.",
    "Asian (other)": "Encompasses a variety of Asian cuisines beyond specific regions, often with rice, noodles, and spices.",
    "Austrian": "Hearty dishes like schnitzel, strudel, and dumplings.",
    "Barbecue": "Slow-cooked meats with smoky flavors, often accompanied by tangy sauces.",
    "Basque": "Cuisine from the Basque region, emphasizing seafood, pintxos, and hearty stews.",
    "Belgian": "Famous for waffles, chocolate, and hearty dishes like moules-frites.",
    "Bistro": "Casual French-inspired dishes like quiche, sandwiches, and salads.",
    "Brazilian": "Known for churrasco (grilled meats), feijoada (black bean stew), and tropical fruits.",
    "British": "Comfort foods like fish and chips, roasts, and hearty pies.",
    "Buffet": "An array of dishes served self-service, often with a mix of cuisines.",
    "Bulgarian": "Features yogurt-based dishes, grilled meats, and fresh vegetables.",
    "Burmese": "Known for its unique mix of Indian, Chinese, and Thai influences, with dishes like tea leaf salad.",
    "Californian": "Fresh, health-focused cuisine often featuring avocados, seafood, and fusion dishes.",
    "Cambodian": "Delicate flavors with dishes like amok (curry), and fresh herbs.",
    "Canadian": "Includes poutine, maple syrup-based dishes, and regional specialties.",
    "Caribbean": "Bold flavors with jerk seasoning, plantains, and seafood.",
    "Chicken": "A focus on chicken-based dishes, grilled, fried, or stewed.",
    "Chinese": "Wide variety of regional cuisines, from Sichuan's spicy dishes to Cantonese dim sum.",
    "Creole-Cajun": "Rich, flavorful dishes like gumbo, jambalaya, and crawfish étouffée.",
    "Crêperie": "Specializes in thin pancakes, both savory and sweet.",
    "Cuban": "A mix of Spanish and Caribbean influences, with dishes like ropa vieja and Cuban sandwiches.",
    "Danish": "Known for pastries, open-faced sandwiches, and hearty stews.",
    "Delicatessen": "Offers prepared foods like sandwiches, cured meats, and cheeses.",
    "Dongbei": "Northeastern Chinese cuisine with hearty, savory flavors.",
    "Doughnuts": "Sweet fried pastries, often glazed or filled.",
    "Ethiopian": "Features communal dishes like injera (flatbread) and spiced stews.",
    "Fast food": "Quick-serve meals like burgers, fries, and tacos.",
    "Fondue": "Melted cheese or chocolate served with bread or fruit for dipping.",
    "French": "Elegant dishes like coq au vin, baguettes, and soufflés.",
    "Fusion": "Combines elements of different culinary traditions.",
    "German": "Known for sausages, pretzels, and hearty stews.",
    "Greek": "Mediterranean flavors with dishes like gyros, moussaka, and baklava.",
    "Grill": "Focus on grilled meats and vegetables, often with smoky flavors.",
    "Guangdong": "Cantonese cuisine, featuring dim sum, roasted meats, and seafood.",
    "Hamburgers": "Ground beef patties served in buns with various toppings.",
    "Hawaiian": "Fusion of Polynesian and Asian flavors, with dishes like poke and kalua pork.",
    "Hot pot": "Interactive dining with ingredients cooked in a communal pot of broth.",
    "Hunan": "Spicy Chinese cuisine with bold, smoky flavors.",
    "Hungarian": "Known for dishes like goulash and paprika-spiced stews.",
    "Ice cream parlor": "Specializes in frozen desserts like ice cream and gelato.",
    "Indian": "Richly spiced dishes like curry, biryani, and naan bread.",
    "Indonesian": "Flavors include satay, nasi goreng, and sambal.",
    "Italian": "Famous for pasta, pizza, and hearty risottos.",
    "Japanese": "Delicate and artful dishes like sushi, ramen, and tempura.",
    "Korean": "Known for kimchi, barbecue, and spicy stews.",
    "Kosher": "Prepared according to Jewish dietary laws.",
    "Lebanese": "Features fresh ingredients in dishes like hummus, tabbouleh, and kebabs.",
    "Macrobiotic": "Focused on whole, plant-based foods for health.",
    "Maghrib": "North African cuisine with dishes like couscous and tagines.",
    "Mediterranean": "Fresh flavors with olive oil, seafood, and vegetables.",
    "Mexican": "Bold, spicy flavors with tacos, enchiladas, and mole.",
    "Middle Eastern": "Dishes like falafel, shawarma, and baklava.",
    "Moroccan": "Known for tagines, couscous, and spiced stews.",
    "Nepalese": "Rich and warming dishes with influences from India and Tibet.",
    "Pakistani": "Boldly spiced curries, kebabs, and rice dishes.",
    "Peruvian": "Features ceviche, quinoa, and hearty stews.",
    "Pizza": "Flatbreads topped with cheese, tomato sauce, and various toppings.",
    "Provençal": "Rustic French cuisine with olive oil, herbs, and fresh produce.",
    "Salad bar": "Offers a variety of salad ingredients for self-assembly.",
    "Sandwich": "Bread filled with meats, cheeses, and spreads.",
    "Scandinavian": "Features seafood, rye bread, and foraged ingredients.",
    "Seafood": "Fresh fish, shellfish, and oceanic delicacies.",
    "Sichuan": "Spicy Chinese cuisine with bold, numbing flavors.",
    "Sicilian": "Italian regional cuisine, emphasizing seafood and citrus.",
    "Snacks": "Light, often portable foods for quick consumption.",
    "Soul food": "Comforting Southern U.S. cuisine, like fried chicken and collard greens.",
    "Soup": "Liquid-based dishes, from broths to creamy chowders.",
    "Spanish": "Known for tapas, paella, and cured meats like jamón.",
    "Steak house": "Specializes in grilled or broiled cuts of beef.",
    "Sudanese": "Traditional dishes with grains, legumes, and stews.",
    "Surinamese": "Fusion cuisine with influences from Africa, Asia, and Europe.",
    "Sushi": "Japanese dish with rice, fish, and seaweed.",
    "Swedish": "Features meatballs, gravlax, and lingonberries.",
    "Swiss": "Known for cheese, chocolate, and fondue.",
    "Syrian": "Middle Eastern cuisine with dishes like kibbeh and fattoush.",
    "Taiwanese": "Street food favorites like bubble tea and beef noodle soup.",
    "Take away": "Meals packaged for off-premises consumption.",
    "Tapas": "Small Spanish dishes served as appetizers or a meal.",
    "Teppanyakki": "Japanese cuisine cooked on an iron griddle.",
    "Thai": "Known for balance of sweet, sour, salty, and spicy flavors.",
    "Tibetan": "Features hearty dumplings and yak-based dishes.",
    "Turkish": "Rich dishes like kebabs, baklava, and meze.",
    "Uruguayan": "Focus on grilled meats and hearty comfort food.",
    "Venezuelan": "Features arepas, empanadas, and rich stews.",
    "Vegetarian": "Plant-based dishes, often featuring fresh vegetables and grains.",
    "Vietnamese": "Light and fresh dishes like pho and banh mi.",
    "Yogurt/juice bar": "Specializes in healthy beverages and yogurt-based treats.",
    "Breakfast": "The first meal of the day, often featuring eggs, toast, pancakes, cereals, or regional specialties."
}

for i in food_related:
    Cuisine(uuid4(), i, food_related[i]).save()

