from uuid import uuid4
from finder_api.models import Cuisine
food_related = {
    "Afghan": "Traditional dishes featuring rice, lamb, and hearty stews, often flavored with dried fruits and nuts.",
    "African": "Diverse cuisines with bold flavors, including ingredients like yams, plantains, and spices.",
    "American": "Wide-ranging cuisine from burgers and barbecue to modern fusion dishes.",
    "Argentinean": "Known for grilled meats, empanadas, and Malbec wines.",
    "Armenian": "Features dishes like kebabs, lavash bread, and dolma.",
    "Asian (other)": "Encompasses a variety of Asian cuisines beyond specific regions, often with rice, noodles, and spices.",
    "Austrian": "Hearty dishes like schnitzel, strudel, and dumplings.",
    "Barbecue": "Slow-cooked meats with smoky flavors, often accompanied by tangy sauces.",
    "Basque": "Cuisine from the Basque region, emphasizing seafood, pintxos, and hearty stews.",
    "Belgian": "Famous for waffles, chocolate, and hearty dishes like moules-frites.",
    "Bistro": "Casual French-inspired dishes like quiche, sandwiches, and salads.",
    "Brazilian": "Known for churrasco (grilled meats), feijoada (black bean stew), and tropical fruits.",
    "British": "Comfort foods like fish and chips, roasts, and hearty pies.",
    "Buffet": "An array of dishes served self-service, often with a mix of cuisines.",
    "Bulgarian": "Features yogurt-based dishes, grilled meats, and fresh vegetables.",
    "Burmese": "Known for its unique mix of Indian, Chinese, and Thai influences, with dishes like tea leaf salad.",
    "Californian": "Fresh, health-focused cuisine often featuring avocados, seafood, and fusion dishes.",
    "Cambodian": "Delicate flavors with dishes like amok (curry), and fresh herbs.",
    "Canadian": "Includes poutine, maple syrup-based dishes, and regional specialties.",
    "Caribbean": "Bold flavors with jerk seasoning, plantains, and seafood.",
    "Chicken": "A focus on chicken-based dishes, grilled, fried, or stewed.",
    "Chinese": "Wide variety of regional cuisines, from Sichuan's spicy dishes to Cantonese dim sum.",
    "Creole-Cajun": "Rich, flavorful dishes like gumbo, jambalaya, and crawfish étouffée.",
    "Crêperie": "Specializes in thin pancakes, both savory and sweet.",
    "Cuban": "A mix of Spanish and Caribbean influences, with dishes like ropa vieja and Cuban sandwiches.",
    "Danish": "Known for pastries, open-faced sandwiches, and hearty stews.",
    "Delicatessen": "Offers prepared foods like sandwiches, cured meats, and cheeses.",
    "Dongbei": "Northeastern Chinese cuisine with hearty, savory flavors.",
    "Doughnuts": "Sweet fried pastries, often glazed or filled.",
    "Ethiopian": "Features communal dishes like injera (flatbread) and spiced stews.",
    "Fast food": "Quick-serve meals like burgers, fries, and tacos.",
    "Fondue": "Melted cheese or chocolate served with bread or fruit for dipping.",
    "French": "Elegant dishes like coq au vin, baguettes, and soufflés.",
    "Fusion": "Combines elements of different culinary traditions.",
    "German": "Known for sausages, pretzels, and hearty stews.",
    "Greek": "Mediterranean flavors with dishes like gyros, moussaka, and baklava.",
    "Grill": "Focus on grilled meats and vegetables, often with smoky flavors.",
    "Guangdong": "Cantonese cuisine, featuring dim sum, roasted meats, and seafood.",
    "Hamburgers": "Ground beef patties served in buns with various toppings.",
    "Hawaiian": "Fusion of Polynesian and Asian flavors, with dishes like poke and kalua pork.",
    "Hot pot": "Interactive dining with ingredients cooked in a communal pot of broth.",
    "Hunan": "Spicy Chinese cuisine with bold, smoky flavors.",
    "Hungarian": "Known for dishes like goulash and paprika-spiced stews.",
    "Ice cream parlor": "Specializes in frozen desserts like ice cream and gelato.",
    "Indian": "Richly spiced dishes like curry, biryani, and naan bread.",
    "Indonesian": "Flavors include satay, nasi goreng, and sambal.",
    "Italian": "Famous for pasta, pizza, and hearty risottos.",
    "Japanese": "Delicate and artful dishes like sushi, ramen, and tempura.",
    "Korean": "Known for kimchi, barbecue, and spicy stews.",
    "Kosher": "Prepared according to Jewish dietary laws.",
    "Lebanese": "Features fresh ingredients in dishes like hummus, tabbouleh, and kebabs.",
    "Macrobiotic": "Focused on whole, plant-based foods for health.",
    "Maghrib": "North African cuisine with dishes like couscous and tagines.",
    "Mediterranean": "Fresh flavors with olive oil, seafood, and vegetables.",
    "Mexican": "Bold, spicy flavors with tacos, enchiladas, and mole.",
    "Middle Eastern": "Dishes like falafel, shawarma, and baklava.",
    "Moroccan": "Known for tagines, couscous, and spiced stews.",
    "Nepalese": "Rich and warming dishes with influences from India and Tibet.",
    "Pakistani": "Boldly spiced curries, kebabs, and rice dishes.",
    "Peruvian": "Features ceviche, quinoa, and hearty stews.",
    "Pizza": "Flatbreads topped with cheese, tomato sauce, and various toppings.",
    "Provençal": "Rustic French cuisine with olive oil, herbs, and fresh produce.",
    "Salad bar": "Offers a variety of salad ingredients for self-assembly.",
    "Sandwich": "Bread filled with meats, cheeses, and spreads.",
    "Scandinavian": "Features seafood, rye bread, and foraged ingredients.",
    "Seafood": "Fresh fish, shellfish, and oceanic delicacies.",
    "Sichuan": "Spicy Chinese cuisine with bold, numbing flavors.",
    "Sicilian": "Italian regional cuisine, emphasizing seafood and citrus.",
    "Snacks": "Light, often portable foods for quick consumption.",
    "Soul food": "Comforting Southern U.S. cuisine, like fried chicken and collard greens.",
    "Soup": "Liquid-based dishes, from broths to creamy chowders.",
    "Spanish": "Known for tapas, paella, and cured meats like jamón.",
    "Steak house": "Specializes in grilled or broiled cuts of beef.",
    "Sudanese": "Traditional dishes with grains, legumes, and stews.",
    "Surinamese": "Fusion cuisine with influences from Africa, Asia, and Europe.",
    "Sushi": "Japanese dish with rice, fish, and seaweed.",
    "Swedish": "Features meatballs, gravlax, and lingonberries.",
    "Swiss": "Known for cheese, chocolate, and fondue.",
    "Syrian": "Middle Eastern cuisine with dishes like kibbeh and fattoush.",
    "Taiwanese": "Street food favorites like bubble tea and beef noodle soup.",
    "Take away": "Meals packaged for off-premises consumption.",
    "Tapas": "Small Spanish dishes served as appetizers or a meal.",
    "Teppanyakki": "Japanese cuisine cooked on an iron griddle.",
    "Thai": "Known for balance of sweet, sour, salty, and spicy flavors.",
    "Tibetan": "Features hearty dumplings and yak-based dishes.",
    "Turkish": "Rich dishes like kebabs, baklava, and meze.",
    "Uruguayan": "Focus on grilled meats and hearty comfort food.",
    "Venezuelan": "Features arepas, empanadas, and rich stews.",
    "Vegetarian": "Plant-based dishes, often featuring fresh vegetables and grains.",
    "Vietnamese": "Light and fresh dishes like pho and banh mi.",
    "Yogurt/juice bar": "Specializes in healthy beverages and yogurt-based treats.",
    "Breakfast": "The first meal of the day, often featuring eggs, toast, pancakes, cereals, or regional specialties.",
    # Existing entries from the earlier list
    "Afghan": "Traditional dishes featuring rice, lamb, and hearty stews, often flavored with dried fruits and nuts.",
    "African": "Diverse cuisines with bold flavors, including ingredients like yams, plantains, and spices.",
    "American": "Wide-ranging cuisine from burgers and barbecue to modern fusion dishes.",
    "Argentinean": "Known for grilled meats, empanadas, and Malbec wines.",
    # Newly added entries
    "Algerian": "North African cuisine featuring tagines, couscous, and harissa-spiced dishes.",
    "Andean": "Traditional mountain food from South America, including quinoa, potatoes, and roasted meats.",
    "Appetizers": "Small starter dishes like finger foods, dips, and spreads.",
    "Arabic": "Middle Eastern cuisine rich in spices, featuring dishes like hummus, kebabs, and baklava.",
    "Azerbaijani": "Flavorful dishes combining Middle Eastern, Central Asian, and Eastern European influences.",
    "Bagels": "Chewy bread rings often served with cream cheese, lox, or sandwich fillings.",
    "Bakery": "Specializes in baked goods such as bread, cakes, pastries, and cookies.",
    "Bavarian": "German regional cuisine with hearty sausages, pretzels, and beer-based dishes.",
    "Belgian Waffles": "Sweet or savory waffles served with a variety of toppings.",
    "Breakfast": "Morning meal items like eggs, pancakes, and cereal.",
    "Bubble Tea": "Sweet, flavored tea with chewy tapioca pearls or other toppings.",
    "Café": "Casual dining with light meals, coffee, and pastries.",
    "Chilean": "Known for fresh seafood, empanadas, and stews like cazuela.",
    "Comfort Food": "Homestyle dishes offering warmth and nostalgia, like casseroles and mac and cheese.",
    "Czech": "Features dumplings, hearty soups, and roasted meats.",
    "Desserts": "Sweet dishes like cakes, ice cream, and puddings.",
    "Dim Sum": "Small bite-sized Cantonese dishes served with tea.",
    "Egyptian": "Features dishes like koshari, ful medames, and molokhia.",
    "Fast Casual": "Quick meals with higher quality ingredients than traditional fast food.",
    "Filipino": "Bold flavors with dishes like adobo, sinigang, and lumpia.",
    "Food Truck": "Mobile vendors offering diverse cuisines and quick meals.",
    "Ghanaian": "Features jollof rice, fufu, and spicy stews.",
    "Healthy": "Focus on nutritious ingredients, often low in calories and fat.",
    "Indigenous American": "Dishes with traditional ingredients like corn, beans, and squash.",
    "Irish": "Comforting dishes like shepherd’s pie, soda bread, and stews.",
    "Israeli": "Middle Eastern dishes like shakshuka, falafel, and hummus.",
    "Jamaican": "Spicy, flavorful dishes like jerk chicken, patties, and rice and peas.",
    "Japanese Street Food": "Casual dishes like takoyaki, okonomiyaki, and yakitori.",
    "Juices & Smoothies": "Fresh, healthy beverages made from fruits, vegetables, and other ingredients.",
    "Kebab": "Grilled and skewered meat served with flatbreads or rice.",
    "Kuwaiti": "Middle Eastern cuisine rich in spices, featuring dishes like machboos and harees.",
    "Laotian": "Known for its use of fresh herbs, sticky rice, and dishes like larb and tam mak hoong.",
    "Malaysian": "Fusion of Malay, Chinese, and Indian influences with dishes like nasi lemak and laksa.",
    "Mongolian": "Hearty and meat-focused dishes often cooked on a hot stone grill.",
    "Mozambican": "Features peri-peri chicken, cassava, and seafood.",
    "Nigerian": "Rich and spicy dishes like suya, egusi soup, and jollof rice.",
    "Nordic": "Minimalist and fresh dishes with fish, rye bread, and berries.",
    "Pakistani Street Food": "Boldly flavored snacks like chaat, samosas, and pakoras.",
    "Pan-Asian": "Fusion of multiple Asian cuisines in one dining experience.",
    "Polish": "Hearty dishes like pierogies, kielbasa, and bigos stew.",
    "Portuguese": "Known for seafood, peri-peri chicken, and egg tarts (pastéis de nata).",
    "Ramen": "Japanese noodle soup with rich broth and various toppings.",
    "Raw Food": "Focus on uncooked and minimally processed foods.",
    "Russian": "Features hearty dishes like borscht, pelmeni, and beef stroganoff.",
    "Scotch": "Scottish dishes like haggis, neeps, and tatties.",
    "Slovak": "Features potato dumplings, cabbage soup, and meat dishes.",
    "South African": "Known for biltong, bobotie, and braai (barbecue).",
    "Street Food": "Casual and portable food often served from carts or stalls.",
    "Tapas Fusion": "Small Spanish-style dishes with influences from other cuisines.",
    "Vegan": "Plant-based dishes free of animal products.",
    "West African": "Bold and spicy dishes like peanut stew and jollof rice.",
    "Wraps": "Flatbreads rolled around fillings like meats, vegetables, and sauces."
}


for i in food_related:
    Cuisine(uuid4(), i, food_related[i]).save()

