# Generated by Django 5.1.3 on 2024-12-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='restraunts', to='finder_api.restraunt'),
        ),
    ]
