# Generated by Django 5.1.4 on 2024-12-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder_api', '0002_restaurant_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='logo',
            field=models.URLField(blank=True, default='', max_length=511),
        ),
    ]
