# Generated by Django 5.1.4 on 2025-01-01 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder_api', '0002_alter_user_profile_image_userfollowing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of the event')),
                ('location', models.CharField(max_length=255, verbose_name='Location of the Event')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255, verbose_name='Description of the event')),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['rating'], 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('uses', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invites',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of the group')),
                ('description', models.CharField(max_length=255, verbose_name='Description of the group')),
                ('is_public', models.BooleanField(default=False)),
                ('events', models.ManyToManyField(related_name='events', to='finder_api.event')),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
                ('invites', models.ManyToManyField(related_name='invites', to='finder_api.invite')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
